---
Name: dashboardconfig
---

SilverStripe\Security\Member:
  extensions:
    - ilateral\SilverStripe\Dashboard\Extensions\DashboardMember

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - ilateral\SilverStripe\Dashboard\Extensions\DashboardSiteConfig

SilverStripe\Forms\GridField\GridFieldDetailForm_ItemRequest:
  extensions:
    - ilateral\SilverStripe\Dashboard\Extensions\DashboardItemEditForm