---
Name: dashboard
---

SilverStripe\Security\Member:
  extensions:
    - UncleCheese\Dashboard\DashboardMember

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - UncleCheese\Dashboard\DashboardSiteConfig

SilverStripe\Forms\GridField\GridFieldDetailForm_ItemRequest:
  extensions:
    - UncleCheese\Dashboard\DashboardItemEditForm

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - unclecheese/dashboard:css/dashboard_icon.css